import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import '../clone.css';
import '../overrides.css';
import MobileSite from '../MobileSite';

// Thai version of the cloned page. Same styles/assets as EN; only the text
// content differs (generated by tools/make-th.mjs). Read per request so
// regenerating clone.th.html shows up without a server restart.
export const dynamic = 'force-dynamic';

export default function Page() {
  const bodyHtml = readFileSync(join(process.cwd(), 'app', 'clone.th.html'), 'utf8');
  return (
    <>
      <div className="clone-desktop" dangerouslySetInnerHTML={{ __html: bodyHtml }} />
      <MobileSite lang="th" />
    </>
  );
}
